cs-printout-server/Controllers/FileManagerController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using cs_printoutserver.Models;
using Microsoft.AspNetCore.Authorization;
using cs_printoutserver.Services.Interfaces;

namespace cs_printoutserver.Controllers
{

    [Route("api/[controller]")]
    [ApiController]
    public class FileManagerController : BaseController<FileManagerController>
    {
        private readonly IOperation _operationService;
        public FileManagerController(IWebHostEnvironment env, IOperation operation)
        {

            _env = env;
            _operationService = operation;
        }

        private Task<string> token
        {
            get
            {
                return _operationService.GetTokenAsync();
            }
        }
        private readonly IWebHostEnvironment _env;
        /// <summary>
        /// Method to upload  a new document into Files folder
        /// </summary>
        /// <param name="program">string</param>
        /// <param name="file">file</param>
        /// <returns></returns>
        /// 
        [Authorize(Policy = "API")]
        [HttpPost("[action]")]
        public async Task<IActionResult> UploadDocument(IFormFile file,[FromForm] string program)

        {
            var result = await _operationService.UploadDocumentAsync(file,program);
            if (result)
                return Ok("Document uploaded correctly.");
            else
                return NotFound("There was an error uploading the file.");

        }

        /// <summary>
        /// Method to download a list with all the existing documents
        /// </summary>
        /// <returns></returns>
        // [Authorize(Policy = "API")]
        [HttpGet("[action]")]
        [Produces("application/json")]
        public IActionResult GetSystemTemplateList()

        {
            brapi result = _operationService.QueryResultSystem();
            return Ok(result);
        }
        /// <summary>
        /// Template list
        /// </summary>
        /// <returns></returns>
        // [Authorize(Policy = "API")]
        [HttpGet("[action]")]
        [Produces("application/json")]
        public IActionResult TemplateList()

        {
            brapi result = _operationService.QueryResultTemplates();
            return Ok(result);
        }
        /// <summary>
        /// Method to download a list with all the existing documents
        /// </summary>
        /// <param name="program">Document</param>
        /// <returns></returns>
        [Authorize(Policy = "API")]
        [HttpGet("[action]")]
        [Produces("application/json")]
        public IActionResult GetDocumentList(string program)

        {
            brapi result = _operationService.QueryResult(program);
            return Ok(result);
        }
        /// <summary>
        /// Method to download a document from Files Folder
        /// </summary>
        /// <param name="file_name">File name</param>
        /// <returns></returns>
        /// 
        [Authorize(Policy = "API")]
        [HttpGet("[action]")]
        public IActionResult DownloadDocument(string file_name)
        {
            var dir = _env.ContentRootPath;
            var path = Path.Combine(dir, "Files", file_name);
            if (!System.IO.File.Exists(path))
            {
                return NotFound("Not found");
            }

            var result = _operationService.DownloadDocument( file_name);
            return result;
        }

        /// <summary>
        /// Delete a Physical Document in PrintOut server
        /// </summary>
        /// <param name="file_name">Report Name</param>
        /// <returns></returns>
        [Authorize(Policy = "API")]
        [HttpDelete("[action]")]

        public async Task<IActionResult>  DeleteDocument(string file_name)
        {
            var path = Path.Combine(_env.ContentRootPath, "Files", file_name);
            if (!System.IO.File.Exists(path))
                return NotFound();
            var result = await _operationService.DeleteFileAsync(path);
            if (result)
                return Ok("Document Deleted correctly.");
            else
                return NotFound("There was an error deleting the file.");

        }

    }

}

cs-printout-server/Views/FileManager/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model cs_printoutserver.Models.FileModel

<div class="text-center">
    <h1 class="display-4">PrintOut File Management </h1>
    <button id="btn1" class="btn btn-outline-success m-1" onclick="GetDocumentList()">Document List</button>
    <button id="btn2" class="btn btn-outline-success m-1" onclick="downloadJson()"><i class="fa fa-download"></i>
    </button>


</div>
<br>



    <form asp-controller="FileManager" asp-action="UploadDocument" enctype="multipart/form-data" method="post">
        <label for="program">Select a program:</label>
        <select name="program" id="programCode" class="form-control">
            @foreach (var program in Model.programList)
            {
                <option value="@program">@program</option>

            }
        </select>
        <label for="file">Select document:</label>
        <input type="file" name="file" class="form-control">



        <input class="btn btn-outline-success m-1" type="submit" value="Upload Document" class="form-control"></input>


    </form>


            <table id="documentTable" class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Document Name</th>
                        <th scope="col">Created</th>
                        <th scope="col">Actions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.fileInfo)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.LastWriteTime</td>
                            <td>
                                <a class="btn btn-outline-success m-1"
                                href="@Url.Action("downloadDocument","FileManager",new { file_name = @item.Name})">Download</a>
                                <a class="btn btn-outline-danger m-1"
                                href="@Url.Action("deleteDocument","FileManager",new { docu_name = @item.Name})">Delete</a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>

@section scripts{

<script type="text/javascript">
    
                    function GetDocumentList()
            {
            var select = document.getElementById('programCode');
            var program = select.options[select.selectedIndex].value;
            console.log(program);
            window.location.href = '@Url.Action("GetDocumentList", "FileManager")?program=' + program;

            }
                    function downloadJson()
            {
            var select = document.getElementById('programCode');
            var program = select.options[select.selectedIndex].value;
            console.log(program);
            window.location.href = '@Url.Action("DownloadJson", "FileManager")?program=' + program;

            }
               
</script>

}